[package]
name = "rust"
version = "0.1.0"
authors = ["Adrien Coulier <adrien.coulier@it.uu.se>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
